# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
before_install:
  - sudo apt-get install libudunits2-dev
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
r_packages:
  - devtools
  - testthat
  - lucode
script:
  - Rscript -e 'devtools::test()'
after_success:
  - Rscript -e 'covr::codecov()'
